# Generated by Django 4.0.3 on 2022-04-18 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mymedia', '0002_a_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A_post',
            new_name='Post',
        ),
    ]
