# Generated by Django 4.0.3 on 2022-04-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0009_photo_delete_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
