# Generated by Django 4.0.3 on 2022-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0010_post_image_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
