# Generated by Django 4.0.3 on 2022-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0011_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
