# Generated by Django 4.0.3 on 2022-06-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0015_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approval',
            field=models.BooleanField(default=True),
        ),
    ]
