# Generated by Django 4.0.3 on 2022-06-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0016_post_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='approval',
            new_name='approved',
        ),
    ]
