# Generated by Django 4.0.3 on 2022-06-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0017_rename_approval_post_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts_to_approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
