# Generated by Django 4.0.3 on 2022-06-05 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0019_delete_posts_to_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts_to_approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='apost', to='Mymedia.post')),
            ],
        ),
    ]
