# Generated by Django 4.0.3 on 2022-06-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0020_posts_to_approve'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts_to_approve',
        ),
    ]
