# Generated by Django 4.0.3 on 2022-06-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0021_delete_posts_to_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnapprovedPost',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Mymedia.post',),
        ),
    ]
