# Generated by Django 4.0.3 on 2022-06-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0022_unapprovedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
