# Generated by Django 4.0.5 on 2022-06-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mymedia', '0023_post_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_id',
        ),
    ]
